services:
  - type: web
    name: njrotc-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHON_EMAIL_CURSE
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true